"""empty message

Revision ID: 76399465b955
Revises: b600917ba10e
Create Date: 2022-05-26 14:18:53.161948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76399465b955'
down_revision = 'b600917ba10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('catogory', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=10), nullable=True),
    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('catogory', sa.VARCHAR(length=140), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###
