"""empty message

Revision ID: b6496e097d7e
Revises: 76399465b955
Create Date: 2022-05-26 17:27:53.326668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6496e097d7e'
down_revision = '76399465b955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.add_column('post', sa.Column('slug', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.drop_column('post', 'catogory')
    op.drop_column('post', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('catogory', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'updated_on')
    op.drop_column('post', 'created_on')
    op.drop_column('post', 'category_id')
    op.drop_column('post', 'slug')
    op.drop_table('post_tags')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###
